FUNCTION zhms_fm_lote_dados.
*"----------------------------------------------------------------------
*"*"Interface local:
*"  IMPORTING
*"     REFERENCE(V_OBJETO) TYPE  CHAR15
*"  EXPORTING
*"     VALUE(V_LOTE) TYPE  ZHMS_DE_LOTE
*"----------------------------------------------------------------------
*" RCP - Tradução EN/ES - 28/08/2018

*  DATA: v_obnum(15) TYPE c.
  DATA v_obnum TYPE tnro-object.

  MOVE v_objeto TO v_obnum.

  CONDENSE v_obnum NO-GAPS.

  CALL FUNCTION 'NUMBER_RANGE_ENQUEUE'
    EXPORTING
      object           = v_obnum   "Create with SNUM
    EXCEPTIONS
      foreign_lock     = 1
      object_not_found = 2
      system_failure   = 3
      OTHERS           = 4.

  CALL FUNCTION 'NUMBER_GET_NEXT'
    EXPORTING
      nr_range_nr
      ='01'
      object                  = v_obnum
    IMPORTING
      number                  = v_lote  "Number generated by SAP
    EXCEPTIONS
      interval_not_found      = 1
      number_range_not_intern = 2
      object_not_found        = 3
      quantity_is_0           = 4
      quantity_is_not_1       = 5
      internal_overflow       = 6
      OTHERS                  = 7.

  CALL FUNCTION 'NUMBER_RANGE_DEQUEUE'
    EXPORTING
      object = v_obnum.

ENDFUNCTION.
