*---------------------------------------------------------------------*
*    view related data declarations
*   generation date: 02.12.2019 at 11:50:34
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZHMS_TB_ATRI_AT.................................*
DATA:  BEGIN OF STATUS_ZHMS_TB_ATRI_AT               .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZHMS_TB_ATRI_AT               .
CONTROLS: TCTRL_ZHMS_TB_ATRI_AT
            TYPE TABLEVIEW USING SCREEN '0046'.
*...processing: ZHMS_TB_CFOP....................................*
DATA:  BEGIN OF STATUS_ZHMS_TB_CFOP                  .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZHMS_TB_CFOP                  .
CONTROLS: TCTRL_ZHMS_TB_CFOP
            TYPE TABLEVIEW USING SCREEN '0039'.
*...processing: ZHMS_TB_CFOP180.................................*
DATA:  BEGIN OF STATUS_ZHMS_TB_CFOP180               .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZHMS_TB_CFOP180               .
CONTROLS: TCTRL_ZHMS_TB_CFOP180
            TYPE TABLEVIEW USING SCREEN '0063'.
*...processing: ZHMS_TB_CF_EMAIL................................*
DATA:  BEGIN OF STATUS_ZHMS_TB_CF_EMAIL              .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZHMS_TB_CF_EMAIL              .
CONTROLS: TCTRL_ZHMS_TB_CF_EMAIL
            TYPE TABLEVIEW USING SCREEN '0037'.
*...processing: ZHMS_TB_CNAE....................................*
DATA:  BEGIN OF STATUS_ZHMS_TB_CNAE                  .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZHMS_TB_CNAE                  .
CONTROLS: TCTRL_ZHMS_TB_CNAE
            TYPE TABLEVIEW USING SCREEN '0020'.
*...processing: ZHMS_TB_CONSUMO.................................*
DATA:  BEGIN OF STATUS_ZHMS_TB_CONSUMO               .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZHMS_TB_CONSUMO               .
CONTROLS: TCTRL_ZHMS_TB_CONSUMO
            TYPE TABLEVIEW USING SCREEN '0045'.
*...processing: ZHMS_TB_DEBUG...................................*
DATA:  BEGIN OF STATUS_ZHMS_TB_DEBUG                 .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZHMS_TB_DEBUG                 .
CONTROLS: TCTRL_ZHMS_TB_DEBUG
            TYPE TABLEVIEW USING SCREEN '0041'.
*...processing: ZHMS_TB_DP_PARVW................................*
DATA:  BEGIN OF STATUS_ZHMS_TB_DP_PARVW              .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZHMS_TB_DP_PARVW              .
CONTROLS: TCTRL_ZHMS_TB_DP_PARVW
            TYPE TABLEVIEW USING SCREEN '0019'.
*...processing: ZHMS_TB_GRPFLD_S................................*
DATA:  BEGIN OF STATUS_ZHMS_TB_GRPFLD_S              .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZHMS_TB_GRPFLD_S              .
CONTROLS: TCTRL_ZHMS_TB_GRPFLD_S
            TYPE TABLEVIEW USING SCREEN '0034'.
*...processing: ZHMS_TB_MAPDATA.................................*
DATA:  BEGIN OF STATUS_ZHMS_TB_MAPDATA               .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZHMS_TB_MAPDATA               .
CONTROLS: TCTRL_ZHMS_TB_MAPDATA
            TYPE TABLEVIEW USING SCREEN '0036'.
*...processing: ZHMS_TB_MESSAGES................................*
DATA:  BEGIN OF STATUS_ZHMS_TB_MESSAGES              .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZHMS_TB_MESSAGES              .
CONTROLS: TCTRL_ZHMS_TB_MESSAGES
            TYPE TABLEVIEW USING SCREEN '0038'.
*...processing: ZHMS_TB_MNEUATR.................................*
DATA:  BEGIN OF STATUS_ZHMS_TB_MNEUATR               .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZHMS_TB_MNEUATR               .
CONTROLS: TCTRL_ZHMS_TB_MNEUATR
            TYPE TABLEVIEW USING SCREEN '0016'.
*...processing: ZHMS_TB_NFEEVT..................................*
DATA:  BEGIN OF STATUS_ZHMS_TB_NFEEVT                .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZHMS_TB_NFEEVT                .
CONTROLS: TCTRL_ZHMS_TB_NFEEVT
            TYPE TABLEVIEW USING SCREEN '0031'.
*...processing: ZHMS_TB_SCEN_FLO................................*
DATA:  BEGIN OF STATUS_ZHMS_TB_SCEN_FLO              .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZHMS_TB_SCEN_FLO              .
CONTROLS: TCTRL_ZHMS_TB_SCEN_FLO
            TYPE TABLEVIEW USING SCREEN '0040'.
*...processing: ZHMS_TB_SHOW_LAY................................*
DATA:  BEGIN OF STATUS_ZHMS_TB_SHOW_LAY              .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZHMS_TB_SHOW_LAY              .
CONTROLS: TCTRL_ZHMS_TB_SHOW_LAY
            TYPE TABLEVIEW USING SCREEN '0044'.
*...processing: ZHMS_TB_STATUS_C................................*
DATA:  BEGIN OF STATUS_ZHMS_TB_STATUS_C              .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZHMS_TB_STATUS_C              .
CONTROLS: TCTRL_ZHMS_TB_STATUS_C
            TYPE TABLEVIEW USING SCREEN '0047'.
*...processing: ZHMS_TB_TCONFIG.................................*
DATA:  BEGIN OF STATUS_ZHMS_TB_TCONFIG               .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZHMS_TB_TCONFIG               .
CONTROLS: TCTRL_ZHMS_TB_TCONFIG
            TYPE TABLEVIEW USING SCREEN '0006'.
*...processing: ZHMS_TB_TOOLBAR.................................*
DATA:  BEGIN OF STATUS_ZHMS_TB_TOOLBAR               .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZHMS_TB_TOOLBAR               .
CONTROLS: TCTRL_ZHMS_TB_TOOLBAR
            TYPE TABLEVIEW USING SCREEN '0053'.
*...processing: ZHMS_TB_TPAMB...................................*
DATA:  BEGIN OF STATUS_ZHMS_TB_TPAMB                 .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZHMS_TB_TPAMB                 .
CONTROLS: TCTRL_ZHMS_TB_TPAMB
            TYPE TABLEVIEW USING SCREEN '0033'.
*...processing: ZHMS_TB_UNIT....................................*
DATA:  BEGIN OF STATUS_ZHMS_TB_UNIT                  .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZHMS_TB_UNIT                  .
CONTROLS: TCTRL_ZHMS_TB_UNIT
            TYPE TABLEVIEW USING SCREEN '0043'.
*...processing: ZHMS_TB_USER_RFC................................*
DATA:  BEGIN OF STATUS_ZHMS_TB_USER_RFC              .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZHMS_TB_USER_RFC              .
CONTROLS: TCTRL_ZHMS_TB_USER_RFC
            TYPE TABLEVIEW USING SCREEN '0035'.
*...processing: ZHMS_TB_VLD_TAX.................................*
DATA:  BEGIN OF STATUS_ZHMS_TB_VLD_TAX               .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZHMS_TB_VLD_TAX               .
CONTROLS: TCTRL_ZHMS_TB_VLD_TAX
            TYPE TABLEVIEW USING SCREEN '0042'.
*...processing: ZHMS_VW_DCITM...................................*
TABLES: ZHMS_VW_DCITM, *ZHMS_VW_DCITM. "view work areas
CONTROLS: TCTRL_ZHMS_VW_DCITM
TYPE TABLEVIEW USING SCREEN '0062'.
DATA: BEGIN OF STATUS_ZHMS_VW_DCITM. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_DCITM.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_DCITM_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_DCITM.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_DCITM_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_DCITM_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_DCITM.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_DCITM_TOTAL.

*...processing: ZHMS_VW_EVENTS..................................*
TABLES: ZHMS_VW_EVENTS, *ZHMS_VW_EVENTS. "view work areas
CONTROLS: TCTRL_ZHMS_VW_EVENTS
TYPE TABLEVIEW USING SCREEN '0003'.
DATA: BEGIN OF STATUS_ZHMS_VW_EVENTS. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_EVENTS.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_EVENTS_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_EVENTS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_EVENTS_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_EVENTS_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_EVENTS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_EVENTS_TOTAL.

*...processing: ZHMS_VW_EVVL_ATR................................*
TABLES: ZHMS_VW_EVVL_ATR, *ZHMS_VW_EVVL_ATR. "view work areas
CONTROLS: TCTRL_ZHMS_VW_EVVL_ATR
TYPE TABLEVIEW USING SCREEN '0008'.
DATA: BEGIN OF STATUS_ZHMS_VW_EVVL_ATR. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_EVVL_ATR.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_EVVL_ATR_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_EVVL_ATR.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_EVVL_ATR_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_EVVL_ATR_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_EVVL_ATR.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_EVVL_ATR_TOTAL.

*...processing: ZHMS_VW_EVV_LAYT................................*
TABLES: ZHMS_VW_EVV_LAYT, *ZHMS_VW_EVV_LAYT. "view work areas
CONTROLS: TCTRL_ZHMS_VW_EVV_LAYT
TYPE TABLEVIEW USING SCREEN '0005'.
DATA: BEGIN OF STATUS_ZHMS_VW_EVV_LAYT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_EVV_LAYT.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_EVV_LAYT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_EVV_LAYT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_EVV_LAYT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_EVV_LAYT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_EVV_LAYT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_EVV_LAYT_TOTAL.

*...processing: ZHMS_VW_EV_FLOW.................................*
TABLES: ZHMS_VW_EV_FLOW, *ZHMS_VW_EV_FLOW. "view work areas
CONTROLS: TCTRL_ZHMS_VW_EV_FLOW
TYPE TABLEVIEW USING SCREEN '0029'.
DATA: BEGIN OF STATUS_ZHMS_VW_EV_FLOW. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_EV_FLOW.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_EV_FLOW_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_EV_FLOW.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_EV_FLOW_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_EV_FLOW_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_EV_FLOW.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_EV_FLOW_TOTAL.

*...processing: ZHMS_VW_EV_VRS..................................*
TABLES: ZHMS_VW_EV_VRS, *ZHMS_VW_EV_VRS. "view work areas
CONTROLS: TCTRL_ZHMS_VW_EV_VRS
TYPE TABLEVIEW USING SCREEN '0004'.
DATA: BEGIN OF STATUS_ZHMS_VW_EV_VRS. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_EV_VRS.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_EV_VRS_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_EV_VRS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_EV_VRS_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_EV_VRS_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_EV_VRS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_EV_VRS_TOTAL.

*...processing: ZHMS_VW_FILDCITM................................*
TABLES: ZHMS_VW_FILDCITM, *ZHMS_VW_FILDCITM. "view work areas
CONTROLS: TCTRL_ZHMS_VW_FILDCITM
TYPE TABLEVIEW USING SCREEN '0061'.
DATA: BEGIN OF STATUS_ZHMS_VW_FILDCITM. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_FILDCITM.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_FILDCITM_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_FILDCITM.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_FILDCITM_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_FILDCITM_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_FILDCITM.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_FILDCITM_TOTAL.

*...processing: ZHMS_VW_GATE....................................*
TABLES: ZHMS_VW_GATE, *ZHMS_VW_GATE. "view work areas
CONTROLS: TCTRL_ZHMS_VW_GATE
TYPE TABLEVIEW USING SCREEN '0021'.
DATA: BEGIN OF STATUS_ZHMS_VW_GATE. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_GATE.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_GATE_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_GATE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_GATE_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_GATE_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_GATE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_GATE_TOTAL.

*...processing: ZHMS_VW_GATEMNEU................................*
TABLES: ZHMS_VW_GATEMNEU, *ZHMS_VW_GATEMNEU. "view work areas
CONTROLS: TCTRL_ZHMS_VW_GATEMNEU
TYPE TABLEVIEW USING SCREEN '0022'.
DATA: BEGIN OF STATUS_ZHMS_VW_GATEMNEU. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_GATEMNEU.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_GATEMNEU_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_GATEMNEU.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_GATEMNEU_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_GATEMNEU_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_GATEMNEU.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_GATEMNEU_TOTAL.

*...processing: ZHMS_VW_GATEOBS.................................*
TABLES: ZHMS_VW_GATEOBS, *ZHMS_VW_GATEOBS. "view work areas
CONTROLS: TCTRL_ZHMS_VW_GATEOBS
TYPE TABLEVIEW USING SCREEN '0023'.
DATA: BEGIN OF STATUS_ZHMS_VW_GATEOBS. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_GATEOBS.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_GATEOBS_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_GATEOBS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_GATEOBS_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_GATEOBS_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_GATEOBS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_GATEOBS_TOTAL.

*...processing: ZHMS_VW_GRPFLD..................................*
TABLES: ZHMS_VW_GRPFLD, *ZHMS_VW_GRPFLD. "view work areas
CONTROLS: TCTRL_ZHMS_VW_GRPFLD
TYPE TABLEVIEW USING SCREEN '0017'.
DATA: BEGIN OF STATUS_ZHMS_VW_GRPFLD. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_GRPFLD.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_GRPFLD_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_GRPFLD.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_GRPFLD_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_GRPFLD_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_GRPFLD.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_GRPFLD_TOTAL.

*...processing: ZHMS_VW_GRPFLD_S................................*
TABLES: ZHMS_VW_GRPFLD_S, *ZHMS_VW_GRPFLD_S. "view work areas
CONTROLS: TCTRL_ZHMS_VW_GRPFLD_S
TYPE TABLEVIEW USING SCREEN '0018'.
DATA: BEGIN OF STATUS_ZHMS_VW_GRPFLD_S. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_GRPFLD_S.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_GRPFLD_S_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_GRPFLD_S.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_GRPFLD_S_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_GRPFLD_S_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_GRPFLD_S.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_GRPFLD_S_TOTAL.

*...processing: ZHMS_VW_MAPCONEC................................*
TABLES: ZHMS_VW_MAPCONEC, *ZHMS_VW_MAPCONEC. "view work areas
CONTROLS: TCTRL_ZHMS_VW_MAPCONEC
TYPE TABLEVIEW USING SCREEN '0032'.
DATA: BEGIN OF STATUS_ZHMS_VW_MAPCONEC. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_MAPCONEC.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_MAPCONEC_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_MAPCONEC.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MAPCONEC_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_MAPCONEC_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_MAPCONEC.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MAPCONEC_TOTAL.

*...processing: ZHMS_VW_MAPDATA.................................*
TABLES: ZHMS_VW_MAPDATA, *ZHMS_VW_MAPDATA. "view work areas
CONTROLS: TCTRL_ZHMS_VW_MAPDATA
TYPE TABLEVIEW USING SCREEN '0051'.
DATA: BEGIN OF STATUS_ZHMS_VW_MAPDATA. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_MAPDATA.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_MAPDATA_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_MAPDATA.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MAPDATA_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_MAPDATA_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_MAPDATA.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MAPDATA_TOTAL.

*...processing: ZHMS_VW_MAPDATAC................................*
TABLES: ZHMS_VW_MAPDATAC, *ZHMS_VW_MAPDATAC. "view work areas
CONTROLS: TCTRL_ZHMS_VW_MAPDATAC
TYPE TABLEVIEW USING SCREEN '0058'.
DATA: BEGIN OF STATUS_ZHMS_VW_MAPDATAC. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_MAPDATAC.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_MAPDATAC_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_MAPDATAC.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MAPDATAC_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_MAPDATAC_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_MAPDATAC.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MAPDATAC_TOTAL.

*...processing: ZHMS_VW_MAPPCONE................................*
TABLES: ZHMS_VW_MAPPCONE, *ZHMS_VW_MAPPCONE. "view work areas
CONTROLS: TCTRL_ZHMS_VW_MAPPCONE
TYPE TABLEVIEW USING SCREEN '0057'.
DATA: BEGIN OF STATUS_ZHMS_VW_MAPPCONE. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_MAPPCONE.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_MAPPCONE_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_MAPPCONE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MAPPCONE_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_MAPPCONE_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_MAPPCONE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MAPPCONE_TOTAL.

*...processing: ZHMS_VW_MAPPING.................................*
TABLES: ZHMS_VW_MAPPING, *ZHMS_VW_MAPPING. "view work areas
CONTROLS: TCTRL_ZHMS_VW_MAPPING
TYPE TABLEVIEW USING SCREEN '0050'.
DATA: BEGIN OF STATUS_ZHMS_VW_MAPPING. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_MAPPING.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_MAPPING_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_MAPPING.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MAPPING_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_MAPPING_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_MAPPING.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MAPPING_TOTAL.

*...processing: ZHMS_VW_MESSAGIN................................*
TABLES: ZHMS_VW_MESSAGIN, *ZHMS_VW_MESSAGIN. "view work areas
CONTROLS: TCTRL_ZHMS_VW_MESSAGIN
TYPE TABLEVIEW USING SCREEN '0007'.
DATA: BEGIN OF STATUS_ZHMS_VW_MESSAGIN. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_MESSAGIN.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_MESSAGIN_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_MESSAGIN.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MESSAGIN_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_MESSAGIN_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_MESSAGIN.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MESSAGIN_TOTAL.

*...processing: ZHMS_VW_MSGEVL_A................................*
TABLES: ZHMS_VW_MSGEVL_A, *ZHMS_VW_MSGEVL_A. "view work areas
CONTROLS: TCTRL_ZHMS_VW_MSGEVL_A
TYPE TABLEVIEW USING SCREEN '0012'.
DATA: BEGIN OF STATUS_ZHMS_VW_MSGEVL_A. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_MSGEVL_A.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_MSGEVL_A_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_MSGEVL_A.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MSGEVL_A_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_MSGEVL_A_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_MSGEVL_A.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MSGEVL_A_TOTAL.

*...processing: ZHMS_VW_MSGEVM_A................................*
TABLES: ZHMS_VW_MSGEVM_A, *ZHMS_VW_MSGEVM_A. "view work areas
CONTROLS: TCTRL_ZHMS_VW_MSGEVM_A
TYPE TABLEVIEW USING SCREEN '0014'.
DATA: BEGIN OF STATUS_ZHMS_VW_MSGEVM_A. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_MSGEVM_A.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_MSGEVM_A_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_MSGEVM_A.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MSGEVM_A_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_MSGEVM_A_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_MSGEVM_A.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MSGEVM_A_TOTAL.

*...processing: ZHMS_VW_MSGEV_LT................................*
TABLES: ZHMS_VW_MSGEV_LT, *ZHMS_VW_MSGEV_LT. "view work areas
CONTROLS: TCTRL_ZHMS_VW_MSGEV_LT
TYPE TABLEVIEW USING SCREEN '0011'.
DATA: BEGIN OF STATUS_ZHMS_VW_MSGEV_LT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_MSGEV_LT.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_MSGEV_LT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_MSGEV_LT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MSGEV_LT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_MSGEV_LT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_MSGEV_LT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MSGEV_LT_TOTAL.

*...processing: ZHMS_VW_MSGEV_MT................................*
TABLES: ZHMS_VW_MSGEV_MT, *ZHMS_VW_MSGEV_MT. "view work areas
CONTROLS: TCTRL_ZHMS_VW_MSGEV_MT
TYPE TABLEVIEW USING SCREEN '0013'.
DATA: BEGIN OF STATUS_ZHMS_VW_MSGEV_MT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_MSGEV_MT.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_MSGEV_MT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_MSGEV_MT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MSGEV_MT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_MSGEV_MT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_MSGEV_MT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MSGEV_MT_TOTAL.

*...processing: ZHMS_VW_MSGE_VRS................................*
TABLES: ZHMS_VW_MSGE_VRS, *ZHMS_VW_MSGE_VRS. "view work areas
CONTROLS: TCTRL_ZHMS_VW_MSGE_VRS
TYPE TABLEVIEW USING SCREEN '0010'.
DATA: BEGIN OF STATUS_ZHMS_VW_MSGE_VRS. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_MSGE_VRS.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_MSGE_VRS_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_MSGE_VRS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MSGE_VRS_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_MSGE_VRS_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_MSGE_VRS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MSGE_VRS_TOTAL.

*...processing: ZHMS_VW_MSG_EVEN................................*
TABLES: ZHMS_VW_MSG_EVEN, *ZHMS_VW_MSG_EVEN. "view work areas
CONTROLS: TCTRL_ZHMS_VW_MSG_EVEN
TYPE TABLEVIEW USING SCREEN '0009'.
DATA: BEGIN OF STATUS_ZHMS_VW_MSG_EVEN. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_MSG_EVEN.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_MSG_EVEN_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_MSG_EVEN.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MSG_EVEN_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_MSG_EVEN_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_MSG_EVEN.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MSG_EVEN_TOTAL.

*...processing: ZHMS_VW_NATURE..................................*
TABLES: ZHMS_VW_NATURE, *ZHMS_VW_NATURE. "view work areas
CONTROLS: TCTRL_ZHMS_VW_NATURE
TYPE TABLEVIEW USING SCREEN '0001'.
DATA: BEGIN OF STATUS_ZHMS_VW_NATURE. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_NATURE.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_NATURE_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_NATURE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_NATURE_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_NATURE_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_NATURE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_NATURE_TOTAL.

*...processing: ZHMS_VW_PKGVLD..................................*
TABLES: ZHMS_VW_PKGVLD, *ZHMS_VW_PKGVLD. "view work areas
CONTROLS: TCTRL_ZHMS_VW_PKGVLD
TYPE TABLEVIEW USING SCREEN '0026'.
DATA: BEGIN OF STATUS_ZHMS_VW_PKGVLD. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_PKGVLD.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_PKGVLD_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_PKGVLD.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_PKGVLD_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_PKGVLD_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_PKGVLD.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_PKGVLD_TOTAL.

*...processing: ZHMS_VW_REGVLD..................................*
TABLES: ZHMS_VW_REGVLD, *ZHMS_VW_REGVLD. "view work areas
CONTROLS: TCTRL_ZHMS_VW_REGVLD
TYPE TABLEVIEW USING SCREEN '0027'.
DATA: BEGIN OF STATUS_ZHMS_VW_REGVLD. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_REGVLD.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_REGVLD_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_REGVLD.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_REGVLD_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_REGVLD_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_REGVLD.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_REGVLD_TOTAL.

*...processing: ZHMS_VW_SCENARIO................................*
TABLES: ZHMS_VW_SCENARIO, *ZHMS_VW_SCENARIO. "view work areas
CONTROLS: TCTRL_ZHMS_VW_SCENARIO
TYPE TABLEVIEW USING SCREEN '0015'.
DATA: BEGIN OF STATUS_ZHMS_VW_SCENARIO. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_SCENARIO.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_SCENARIO_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_SCENARIO.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_SCENARIO_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_SCENARIO_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_SCENARIO.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_SCENARIO_TOTAL.

*...processing: ZHMS_VW_SCENFLOC................................*
TABLES: ZHMS_VW_SCENFLOC, *ZHMS_VW_SCENFLOC. "view work areas
CONTROLS: TCTRL_ZHMS_VW_SCENFLOC
TYPE TABLEVIEW USING SCREEN '0055'.
DATA: BEGIN OF STATUS_ZHMS_VW_SCENFLOC. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_SCENFLOC.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_SCENFLOC_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_SCENFLOC.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_SCENFLOC_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_SCENFLOC_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_SCENFLOC.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_SCENFLOC_TOTAL.

*...processing: ZHMS_VW_SCEN_FLO................................*
TABLES: ZHMS_VW_SCEN_FLO, *ZHMS_VW_SCEN_FLO. "view work areas
CONTROLS: TCTRL_ZHMS_VW_SCEN_FLO
TYPE TABLEVIEW USING SCREEN '0024'.
DATA: BEGIN OF STATUS_ZHMS_VW_SCEN_FLO. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_SCEN_FLO.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_SCEN_FLO_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_SCEN_FLO.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_SCEN_FLO_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_SCEN_FLO_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_SCEN_FLO.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_SCEN_FLO_TOTAL.

*...processing: ZHMS_VW_SECURITY................................*
TABLES: ZHMS_VW_SECURITY, *ZHMS_VW_SECURITY. "view work areas
CONTROLS: TCTRL_ZHMS_VW_SECURITY
TYPE TABLEVIEW USING SCREEN '0064'.
DATA: BEGIN OF STATUS_ZHMS_VW_SECURITY. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_SECURITY.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_SECURITY_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_SECURITY.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_SECURITY_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_SECURITY_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_SECURITY.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_SECURITY_TOTAL.

*...processing: ZHMS_VW_TYPE....................................*
TABLES: ZHMS_VW_TYPE, *ZHMS_VW_TYPE. "view work areas
CONTROLS: TCTRL_ZHMS_VW_TYPE
TYPE TABLEVIEW USING SCREEN '0002'.
DATA: BEGIN OF STATUS_ZHMS_VW_TYPE. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_TYPE.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_TYPE_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_TYPE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_TYPE_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_TYPE_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZHMS_VW_TYPE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_TYPE_TOTAL.

*...not in TVDIR: ZHMS_VW_MAP_LAY...............................*
TABLES: ZHMS_VW_MAP_LAY, *ZHMS_VW_MAP_LAY. "view work areas
CONTROLS: TCTRL_ZHMS_VW_MAP_LAY
TYPE TABLEVIEW USING SCREEN '0000'.
DATA: BEGIN OF STATUS_ZHMS_VW_MAP_LAY. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZHMS_VW_MAP_LAY.
* Table for entries selected to show on screen
DATA: BEGIN OF ZHMS_VW_MAP_LAY_EXTRACT OCCURS 0001.
INCLUDE STRUCTURE ZHMS_VW_MAP_LAY.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MAP_LAY_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZHMS_VW_MAP_LAY_TOTAL OCCURS 0001.
INCLUDE STRUCTURE ZHMS_VW_MAP_LAY.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZHMS_VW_MAP_LAY_TOTAL.

*.........table declarations:.................................*
TABLES: *ZHMS_TB_ATRI_AT               .
TABLES: *ZHMS_TB_CFOP                  .
TABLES: *ZHMS_TB_CFOP180               .
TABLES: *ZHMS_TB_CF_EMAIL              .
TABLES: *ZHMS_TB_CNAE                  .
TABLES: *ZHMS_TB_CONSUMO               .
TABLES: *ZHMS_TB_DEBUG                 .
TABLES: *ZHMS_TB_DP_PARVW              .
TABLES: *ZHMS_TB_GRPFLD_S              .
TABLES: *ZHMS_TB_MAPDATA               .
TABLES: *ZHMS_TB_MESSAGES              .
TABLES: *ZHMS_TB_MNEUATR               .
TABLES: *ZHMS_TB_NFEEVT                .
TABLES: *ZHMS_TB_SCEN_FLO              .
TABLES: *ZHMS_TB_SHOW_LAY              .
TABLES: *ZHMS_TB_STATUS_C              .
TABLES: *ZHMS_TB_TCONFIG               .
TABLES: *ZHMS_TB_TOOLBAR               .
TABLES: *ZHMS_TB_TPAMB                 .
TABLES: *ZHMS_TB_UNIT                  .
TABLES: *ZHMS_TB_USER_RFC              .
TABLES: *ZHMS_TB_VLD_TAX               .
TABLES: *ZHMS_TX_SCEN_FLO              .
TABLES: ZHMS_TB_ATRI_AT                .
TABLES: ZHMS_TB_CFOP                   .
TABLES: ZHMS_TB_CFOP180                .
TABLES: ZHMS_TB_CF_EMAIL               .
TABLES: ZHMS_TB_CNAE                   .
TABLES: ZHMS_TB_CONSUMO                .
TABLES: ZHMS_TB_DCITM                  .
TABLES: ZHMS_TB_DEBUG                  .
TABLES: ZHMS_TB_DP_PARVW               .
TABLES: ZHMS_TB_EVENTS                 .
TABLES: ZHMS_TB_EVVL_ATR               .
TABLES: ZHMS_TB_EVV_LAYT               .
TABLES: ZHMS_TB_EV_FLOW                .
TABLES: ZHMS_TB_EV_VRS                 .
TABLES: ZHMS_TB_FILDCITM               .
TABLES: ZHMS_TB_GATE                   .
TABLES: ZHMS_TB_GATEMNEU               .
TABLES: ZHMS_TB_GATEOBS                .
TABLES: ZHMS_TB_GRPFLD                 .
TABLES: ZHMS_TB_GRPFLD_S               .
TABLES: ZHMS_TB_MAPCONEC               .
TABLES: ZHMS_TB_MAPDATA                .
TABLES: ZHMS_TB_MAPDATAC               .
TABLES: ZHMS_TB_MAPPCONE               .
TABLES: ZHMS_TB_MAPPING                .
TABLES: ZHMS_TB_MESSAGES               .
TABLES: ZHMS_TB_MESSAGIN               .
TABLES: ZHMS_TB_MNEUATR                .
TABLES: ZHMS_TB_MSGEVL_A               .
TABLES: ZHMS_TB_MSGEVM_A               .
TABLES: ZHMS_TB_MSGEV_LT               .
TABLES: ZHMS_TB_MSGEV_MT               .
TABLES: ZHMS_TB_MSGE_VRS               .
TABLES: ZHMS_TB_MSG_EVEN               .
TABLES: ZHMS_TB_NATURE                 .
TABLES: ZHMS_TB_NFEEVT                 .
TABLES: ZHMS_TB_PKGVLD                 .
TABLES: ZHMS_TB_REGVLD                 .
TABLES: ZHMS_TB_SCENARIO               .
TABLES: ZHMS_TB_SCENFLOC               .
TABLES: ZHMS_TB_SCEN_FLO               .
TABLES: ZHMS_TB_SECURITY               .
TABLES: ZHMS_TB_SHOW_LAY               .
TABLES: ZHMS_TB_STATUS_C               .
TABLES: ZHMS_TB_TCONFIG                .
TABLES: ZHMS_TB_TOOLBAR                .
TABLES: ZHMS_TB_TPAMB                  .
TABLES: ZHMS_TB_TYPE                   .
TABLES: ZHMS_TB_UNIT                   .
TABLES: ZHMS_TB_USER_RFC               .
TABLES: ZHMS_TB_VLD_TAX                .
TABLES: ZHMS_TX_EVENTS                 .
TABLES: ZHMS_TX_EVV_LAYT               .
TABLES: ZHMS_TX_EV_FLOW                .
TABLES: ZHMS_TX_GATE                   .
TABLES: ZHMS_TX_GATEMNEU               .
TABLES: ZHMS_TX_GRPFLD                 .
TABLES: ZHMS_TX_MAPPING                .
TABLES: ZHMS_TX_MESSAGIN               .
TABLES: ZHMS_TX_NATURE                 .
TABLES: ZHMS_TX_PKGVLD                 .
TABLES: ZHMS_TX_REGVLD                 .
TABLES: ZHMS_TX_SCENARIO               .
TABLES: ZHMS_TX_SCEN_FLO               .
TABLES: ZHMS_TX_TYPE                   .
*.........tables for views not in TVDIR.......................*
TABLES: ZHMS_TB_MAP_LAY                .

* general table data declarations..............
  INCLUDE LSVIMTDT                                .
